version: '2.1'
services:
    api-server:
        network_mode: host
        build: ./web
        ports:
            - "5000:5000"
        environment:
            - FLASK_DEBUG=1
        volumes:
            - ./web:/myapp
